name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Activities
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.activities.svg
          plugin_activity: yes
          plugin_activity_limit: 5           # Limit to 5 events
          plugin_activity_load: 100          # Load up to 100 recent events from API (should be higher than "limit")
          plugin_activity_days: 14           # Keep only events from last 14 days (set to 0 for no limit)
          plugin_activity_filter: all        # Show all events (use table above to filter events types)
          plugin_activity_visibility: all # Only display public events
          plugin_activity_timestamps: yes    # Display events timestamps
          plugin_activity_skipped: "" 
          # Your GitHub token
          token: ${{ secrets.PERSONAL_TOKEN_FOR_METRIC }}
